services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    ports:
      - "8080:8080"
      - "5006:5006"
      - "8082:8082"
      - "8083:8083"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/certs:/certs:ro
      - ./data/caddy:/data
    environment:
      - TAILSCALE_HOST=${TAILSCALE_HOST}
    restart: unless-stopped

  actual_server:
    image: docker.io/actualbudget/actual-server:26.4.0
    container_name: actual_server
    volumes:
      - ./data/actual-budget:/data
    restart: unless-stopped

  nginx:
    image: nginx:1.29.0-alpine
    container_name: nginx
    volumes:
      - ./index.html:/etc/nginx/templates/index.html.template:ro
      - ./favicon.ico:/usr/share/nginx/html/favicon.ico
    environment:
      - TAILSCALE_HOST=${TAILSCALE_HOST}
      - POSTHOG_URL=${POSTHOG_URL}
    command: /bin/sh -c "envsubst '$$TAILSCALE_HOST $$POSTHOG_URL' < /etc/nginx/templates/index.html.template > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
    restart: unless-stopped

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: upsite_dev
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  shiori:
    # image: ghcr.io/go-shiori/shiori:latest
    image: shiori:localdev
    container_name: shiori
    environment:
      SHIORI_DATABASE_URL: ${SHIORI_DATABASE_URL}
      SHIORI_HTTP_SECRET_KEY: ${SHIORI_HTTP_SECRET_KEY}
      SHIORI_SSO_PROXY_AUTH_ENABLED: "true"
      SHIORI_SSO_PROXY_AUTH_HEADER_NAME: Remote-User
      SHIORI_SSO_PROXY_AUTH_TRUSTED: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
    depends_on:
      - postgres
    restart: unless-stopped

  searxng:
    image: docker.io/searxng/searxng:2026.4.7-08ef7a63d
    container_name: searxng
    volumes:
      - ./data/searxng:/etc/searxng
    environment:
      - SEARXNG_BASE_URL=http://localhost:8083/
    restart: unless-stopped

